service: serverless-typescript
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  profile: lambda_user
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - { "Fn::GetAtt": ["CardTable", "Arn"] }
        
resources:
  Resources:    
    CardTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CardTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: token
            AttributeType: S
        KeySchema:
          - AttributeName: token
            KeyType: HASH            
        TimeToLiveSpecification:
          AttributeName: expiration_time
          Enabled: true    

custom:
  dynamodb:
    stages:
      - dev

functions:
  postToken:
    handler: src/infrastructure/driving-adapters/lambda/LambdaDriving.postTokenLambda
    events:
      - httpApi:
          method: post
          path: /v2/tokens
  getToken:
    handler: src/infrastructure/driving-adapters/lambda/LambdaDriving.getTokenLambda
    events:
      - httpApi:
          method: get
          path: /v2/tokens/{token}

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
